"""
Natural Language Geospatial Operations Parser for SatQuery AI
SIH Problem Statement 26167 | Team Vyomix

Parses structured filters and spatial selectors from natural language queries.
Converts supported constraints into safe structured operations using validated schemas.
Never executes arbitrary code generated by NL parsing.
"""
import re
import logging
from typing import Dict, Any, Optional, List, Tuple

logger = logging.getLogger("satquery.agent.nl_geo_ops")


class GeoConstraints:
    """Parsed geospatial constraints from natural language."""

    def __init__(self):
        self.min_area_ha: Optional[float] = None
        self.max_area_ha: Optional[float] = None
        self.spatial_selector: Optional[str] = None  # "northern_half", "southern_half", etc.
        self.count_regions: bool = False
        self.compare_modalities: bool = False
        self.filter_by_type: Optional[str] = None  # "built-up", "vegetation", etc.

    def to_dict(self) -> Dict[str, Any]:
        d = {}
        if self.min_area_ha is not None:
            d["min_area_ha"] = self.min_area_ha
        if self.max_area_ha is not None:
            d["max_area_ha"] = self.max_area_ha
        if self.spatial_selector:
            d["spatial_selector"] = self.spatial_selector
        if self.count_regions:
            d["count_regions"] = True
        if self.compare_modalities:
            d["compare_modalities"] = True
        if self.filter_by_type:
            d["filter_by_type"] = self.filter_by_type
        return d

    def has_constraints(self) -> bool:
        return bool(self.to_dict())


# Area threshold patterns
AREA_PATTERNS = [
    (r"larger than\s+([\d.]+)\s*(?:hectare|ha)", "min"),
    (r"bigger than\s+([\d.]+)\s*(?:hectare|ha)", "min"),
    (r"greater than\s+([\d.]+)\s*(?:hectare|ha)", "min"),
    (r"more than\s+([\d.]+)\s*(?:hectare|ha)", "min"),
    (r"at least\s+([\d.]+)\s*(?:hectare|ha)", "min"),
    (r"exceeding\s+([\d.]+)\s*(?:hectare|ha)", "min"),
    (r"smaller than\s+([\d.]+)\s*(?:hectare|ha)", "max"),
    (r"less than\s+([\d.]+)\s*(?:hectare|ha)", "max"),
    (r"under\s+([\d.]+)\s*(?:hectare|ha)", "max"),
    # Square meters
    (r"larger than\s+([\d.]+)\s*(?:m²|sq\s*m|square\s*meter)", "min_m2"),
    (r"smaller than\s+([\d.]+)\s*(?:m²|sq\s*m|square\s*meter)", "max_m2"),
]

# Spatial selector patterns
SPATIAL_SELECTORS = [
    (r"\b(?:the\s+)?northern\s+half\b", "northern_half"),
    (r"\b(?:the\s+)?southern\s+half\b", "southern_half"),
    (r"\b(?:the\s+)?eastern\s+half\b", "eastern_half"),
    (r"\b(?:the\s+)?western\s+half\b", "western_half"),
    (r"\b(?:the\s+)?upper\s+half\b", "northern_half"),
    (r"\b(?:the\s+)?lower\s+half\b", "southern_half"),
    (r"\b(?:the\s+)?left\s+half\b", "western_half"),
    (r"\b(?:the\s+)?right\s+half\b", "eastern_half"),
    (r"\b(?:the\s+)?northwest(?:ern)?\s+(?:quadrant|quarter|corner)\b", "northwest_quadrant"),
    (r"\b(?:the\s+)?northeast(?:ern)?\s+(?:quadrant|quarter|corner)\b", "northeast_quadrant"),
    (r"\b(?:the\s+)?southwest(?:ern)?\s+(?:quadrant|quarter|corner)\b", "southwest_quadrant"),
    (r"\b(?:the\s+)?southeast(?:ern)?\s+(?:quadrant|quarter|corner)\b", "southeast_quadrant"),
    (r"\b(?:the\s+)?center(?:al)?\s+(?:region|area|part)\b", "center_region"),
]

# Count patterns
COUNT_PATTERNS = [
    r"\bhow many\b",
    r"\bcount\s+(?:the\s+)?(?:number|regions?|areas?|patches?)\b",
    r"\bnumber of\b",
]

# Land cover type filters
TYPE_FILTERS = [
    (r"\bbuilt[\s-]?up\b", "built-up"),
    (r"\burban\b", "urban"),
    (r"\bvegetation\b", "vegetation"),
    (r"\bforest\b", "forest"),
    (r"\bwater\s*(?:body|bodies)?\b", "water"),
    (r"\bbare\s*(?:soil|ground)\b", "bare_soil"),
    (r"\bagricult\w*\b", "agriculture"),
    (r"\bcrop\w*\b", "cropland"),
]


def parse_geo_constraints(query_text: str) -> GeoConstraints:
    """
    Extracts geospatial constraints from a natural language query.
    Returns structured GeoConstraints — never arbitrary code.
    """
    q_lower = query_text.lower().strip()
    constraints = GeoConstraints()

    # 1. Parse area thresholds
    for pattern, bound_type in AREA_PATTERNS:
        match = re.search(pattern, q_lower)
        if match:
            val = float(match.group(1))
            if bound_type == "min":
                constraints.min_area_ha = val
            elif bound_type == "max":
                constraints.max_area_ha = val
            elif bound_type == "min_m2":
                constraints.min_area_ha = val / 10000.0
            elif bound_type == "max_m2":
                constraints.max_area_ha = val / 10000.0

    # 2. Parse spatial selectors
    for pattern, selector in SPATIAL_SELECTORS:
        if re.search(pattern, q_lower):
            constraints.spatial_selector = selector
            break

    # 3. Parse counting requests
    if any(re.search(p, q_lower) for p in COUNT_PATTERNS):
        constraints.count_regions = True

    # 4. Parse modality comparison
    if re.search(r"\bcompare\s+(?:optical|sar|radar)\s+and\s+(?:optical|sar|radar)\b", q_lower):
        constraints.compare_modalities = True

    # 5. Parse type filters
    for pattern, land_type in TYPE_FILTERS:
        if re.search(pattern, q_lower):
            constraints.filter_by_type = land_type
            break

    if constraints.has_constraints():
        logger.info(f"[NL-GeoOps] Parsed constraints: {constraints.to_dict()}")

    return constraints


def spatial_selector_to_aoi(selector: str, image_width: int, image_height: int) -> Dict[str, Any]:
    """
    Converts a spatial selector string to an AOI dict (rectangle bbox in pixels).
    """
    w, h = image_width, image_height
    hw, hh = w // 2, h // 2

    SELECTOR_MAP = {
        "northern_half": [0, 0, w, hh],
        "southern_half": [0, hh, w, h],
        "eastern_half": [hw, 0, w, h],
        "western_half": [0, 0, hw, h],
        "northwest_quadrant": [0, 0, hw, hh],
        "northeast_quadrant": [hw, 0, w, hh],
        "southwest_quadrant": [0, hh, hw, h],
        "southeast_quadrant": [hw, hh, w, h],
        "center_region": [w // 4, h // 4, 3 * w // 4, 3 * h // 4],
    }

    bbox = SELECTOR_MAP.get(selector, [0, 0, w, h])
    return {
        "type": "rectangle",
        "bbox": bbox,
        "coord_system": "pixel",
    }


def filter_regions_by_constraints(
    regions: List[Dict[str, Any]],
    constraints: GeoConstraints,
) -> List[Dict[str, Any]]:
    """
    Filters candidate region dicts by parsed geospatial constraints.
    Supports min_area_ha, max_area_ha, and spatial_selector.
    """
    filtered = []
    for r in regions:
        area_ha = r.get("area_ha", r.get("area_hectares"))
        if constraints.min_area_ha is not None and area_ha is not None:
            if area_ha < constraints.min_area_ha:
                continue
        if constraints.max_area_ha is not None and area_ha is not None:
            if area_ha > constraints.max_area_ha:
                continue
        if constraints.spatial_selector and "bbox" in r:
            ymin = r["bbox"][1]
            if constraints.spatial_selector == "northern_half" and ymin >= 0.5:
                continue
            elif constraints.spatial_selector == "southern_half" and ymin < 0.5:
                continue
        filtered.append(r)
    return filtered
